version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: DoneK
    ports:
      - 5435:5432


  adminer:
    image: adminer
    restart: always
    ports:
      - 8084:8080